-- Seed foods table with 2026 Dietary Guidelines data
-- Tier 1 = +10 points, Tier 2 = +7, Tier 3 = +5, Tier 4 = +3, Tier 5 = +1
-- Tier -5 = -2 points, Tier -4 = -4, Tier -3 = -6, Tier -2 = -8, Tier -1 = -10

INSERT INTO foods (name, category, subcategory, tier, points) VALUES
-- TIER 1: TOP OF PYRAMID (+10 points)
-- Beef
('Steak (ribeye)', 'Protein', 'Beef', 1, 10),
('Steak (sirloin)', 'Protein', 'Beef', 1, 10),
('Steak (filet mignon)', 'Protein', 'Beef', 1, 10),
('Steak (NY strip)', 'Protein', 'Beef', 1, 10),
('Steak (flank)', 'Protein', 'Beef', 1, 10),
('Ground beef', 'Protein', 'Beef', 1, 10),
('Beef roast', 'Protein', 'Beef', 1, 10),
('Beef liver', 'Protein', 'Beef', 1, 10),
('Beef short ribs', 'Protein', 'Beef', 1, 10),
('Brisket', 'Protein', 'Beef', 1, 10),

-- Poultry
('Chicken breast', 'Protein', 'Poultry', 1, 10),
('Chicken thigh', 'Protein', 'Poultry', 1, 10),
('Chicken drumstick', 'Protein', 'Poultry', 1, 10),
('Chicken wings (plain)', 'Protein', 'Poultry', 1, 10),
('Whole roasted chicken', 'Protein', 'Poultry', 1, 10),
('Ground chicken', 'Protein', 'Poultry', 1, 10),
('Turkey breast', 'Protein', 'Poultry', 1, 10),
('Ground turkey', 'Protein', 'Poultry', 1, 10),
('Turkey leg', 'Protein', 'Poultry', 1, 10),
('Duck breast', 'Protein', 'Poultry', 1, 10),

-- Fish & Seafood
('Salmon (wild-caught)', 'Protein', 'Fish', 1, 10),
('Salmon (Atlantic)', 'Protein', 'Fish', 1, 10),
('Sardines', 'Protein', 'Fish', 1, 10),
('Mackerel', 'Protein', 'Fish', 1, 10),
('Tuna (fresh)', 'Protein', 'Fish', 1, 10),
('Tuna (canned)', 'Protein', 'Fish', 1, 10),
('Cod', 'Protein', 'Fish', 1, 10),
('Halibut', 'Protein', 'Fish', 1, 10),
('Trout', 'Protein', 'Fish', 1, 10),
('Sea bass', 'Protein', 'Fish', 1, 10),
('Shrimp', 'Protein', 'Seafood', 1, 10),
('Lobster', 'Protein', 'Seafood', 1, 10),
('Crab', 'Protein', 'Seafood', 1, 10),
('Scallops', 'Protein', 'Seafood', 1, 10),
('Mussels', 'Protein', 'Seafood', 1, 10),
('Oysters', 'Protein', 'Seafood', 1, 10),

-- Pork
('Pork chop', 'Protein', 'Pork', 1, 10),
('Pork tenderloin', 'Protein', 'Pork', 1, 10),
('Pork loin', 'Protein', 'Pork', 1, 10),
('Ground pork', 'Protein', 'Pork', 1, 10),
('Ham (uncured)', 'Protein', 'Pork', 1, 10),

-- Other Meats
('Lamb chop', 'Protein', 'Lamb', 1, 10),
('Ground lamb', 'Protein', 'Lamb', 1, 10),
('Bison', 'Protein', 'Game', 1, 10),
('Venison', 'Protein', 'Game', 1, 10),

-- Eggs
('Eggs (whole)', 'Protein', 'Eggs', 1, 10),
('Egg whites', 'Protein', 'Eggs', 1, 10),

-- Cheese
('Cheddar cheese', 'Dairy', 'Cheese', 1, 10),
('Parmesan cheese', 'Dairy', 'Cheese', 1, 10),
('Mozzarella cheese', 'Dairy', 'Cheese', 1, 10),
('Gouda cheese', 'Dairy', 'Cheese', 1, 10),
('Brie cheese', 'Dairy', 'Cheese', 1, 10),
('Swiss cheese', 'Dairy', 'Cheese', 1, 10),
('Feta cheese', 'Dairy', 'Cheese', 1, 10),
('Blue cheese', 'Dairy', 'Cheese', 1, 10),
('Goat cheese', 'Dairy', 'Cheese', 1, 10),
('Cottage cheese', 'Dairy', 'Cheese', 1, 10),
('Cream cheese', 'Dairy', 'Cheese', 1, 10),
('Ricotta cheese', 'Dairy', 'Cheese', 1, 10),

-- Dairy
('Whole milk', 'Dairy', 'Milk', 1, 10),
('Heavy cream', 'Dairy', 'Cream', 1, 10),
('Greek yogurt (plain)', 'Dairy', 'Yogurt', 1, 10),
('Butter', 'Dairy', 'Butter', 1, 10),
('Ghee', 'Dairy', 'Butter', 1, 10),
('Sour cream', 'Dairy', 'Cream', 1, 10),
('Kefir (plain)', 'Dairy', 'Fermented', 1, 10),

-- Healthy Fats
('Olive oil', 'Fats', 'Oil', 1, 10),
('Avocado oil', 'Fats', 'Oil', 1, 10),
('Coconut oil', 'Fats', 'Oil', 1, 10),

-- Nuts
('Almonds', 'Fats', 'Nuts', 1, 10),
('Walnuts', 'Fats', 'Nuts', 1, 10),
('Macadamia nuts', 'Fats', 'Nuts', 1, 10),
('Pecans', 'Fats', 'Nuts', 1, 10),
('Brazil nuts', 'Fats', 'Nuts', 1, 10),
('Cashews', 'Fats', 'Nuts', 1, 10),
('Pistachios', 'Fats', 'Nuts', 1, 10),

-- Seeds
('Chia seeds', 'Fats', 'Seeds', 1, 10),
('Flax seeds', 'Fats', 'Seeds', 1, 10),
('Pumpkin seeds', 'Fats', 'Seeds', 1, 10),
('Sunflower seeds', 'Fats', 'Seeds', 1, 10),
('Hemp seeds', 'Fats', 'Seeds', 1, 10),

-- Non-starchy Vegetables
('Broccoli', 'Vegetables', 'Cruciferous', 1, 10),
('Cauliflower', 'Vegetables', 'Cruciferous', 1, 10),
('Brussels sprouts', 'Vegetables', 'Cruciferous', 1, 10),
('Cabbage', 'Vegetables', 'Cruciferous', 1, 10),
('Kale', 'Vegetables', 'Leafy Greens', 1, 10),
('Spinach', 'Vegetables', 'Leafy Greens', 1, 10),
('Arugula', 'Vegetables', 'Leafy Greens', 1, 10),
('Romaine lettuce', 'Vegetables', 'Leafy Greens', 1, 10),
('Swiss chard', 'Vegetables', 'Leafy Greens', 1, 10),
('Collard greens', 'Vegetables', 'Leafy Greens', 1, 10),
('Asparagus', 'Vegetables', 'Green', 1, 10),
('Green beans', 'Vegetables', 'Green', 1, 10),
('Zucchini', 'Vegetables', 'Squash', 1, 10),
('Cucumber', 'Vegetables', 'Green', 1, 10),
('Celery', 'Vegetables', 'Green', 1, 10),
('Bell pepper', 'Vegetables', 'Pepper', 1, 10),
('Mushrooms', 'Vegetables', 'Fungi', 1, 10),
('Tomato', 'Vegetables', 'Nightshade', 1, 10),
('Onion', 'Vegetables', 'Allium', 1, 10),
('Garlic', 'Vegetables', 'Allium', 1, 10),
('Eggplant', 'Vegetables', 'Nightshade', 1, 10),
('Artichoke', 'Vegetables', 'Thistle', 1, 10),
('Avocado', 'Vegetables', 'Fruit', 1, 10),
('Sauerkraut', 'Vegetables', 'Fermented', 1, 10),
('Kimchi', 'Vegetables', 'Fermented', 1, 10),

-- TIER 2: UPPER PYRAMID (+7 points)
-- Berries
('Blueberries', 'Fruit', 'Berries', 2, 7),
('Strawberries', 'Fruit', 'Berries', 2, 7),
('Raspberries', 'Fruit', 'Berries', 2, 7),
('Blackberries', 'Fruit', 'Berries', 2, 7),
('Cranberries', 'Fruit', 'Berries', 2, 7),

-- Citrus
('Orange', 'Fruit', 'Citrus', 2, 7),
('Grapefruit', 'Fruit', 'Citrus', 2, 7),
('Lemon', 'Fruit', 'Citrus', 2, 7),
('Lime', 'Fruit', 'Citrus', 2, 7),

-- Other Fruits
('Apple', 'Fruit', 'Pome', 2, 7),
('Pear', 'Fruit', 'Pome', 2, 7),
('Peach', 'Fruit', 'Stone', 2, 7),
('Plum', 'Fruit', 'Stone', 2, 7),
('Cherry', 'Fruit', 'Stone', 2, 7),
('Grapes', 'Fruit', 'Vine', 2, 7),
('Kiwi', 'Fruit', 'Tropical', 2, 7),
('Mango', 'Fruit', 'Tropical', 2, 7),
('Pineapple', 'Fruit', 'Tropical', 2, 7),
('Papaya', 'Fruit', 'Tropical', 2, 7),
('Watermelon', 'Fruit', 'Melon', 2, 7),
('Cantaloupe', 'Fruit', 'Melon', 2, 7),
('Banana', 'Fruit', 'Tropical', 2, 7),
('Pomegranate', 'Fruit', 'Other', 2, 7),

-- Legumes
('Lentils', 'Legumes', 'Lentils', 2, 7),
('Black beans', 'Legumes', 'Beans', 2, 7),
('Kidney beans', 'Legumes', 'Beans', 2, 7),
('Chickpeas', 'Legumes', 'Beans', 2, 7),
('Pinto beans', 'Legumes', 'Beans', 2, 7),
('Navy beans', 'Legumes', 'Beans', 2, 7),
('Edamame', 'Legumes', 'Soy', 2, 7),
('Hummus', 'Legumes', 'Prepared', 2, 7),

-- Plant Proteins
('Tofu', 'Protein', 'Plant', 2, 7),
('Tempeh', 'Protein', 'Plant', 2, 7),

-- TIER 3: MIDDLE PYRAMID (+5 points)
-- Starchy Vegetables
('Sweet potato', 'Vegetables', 'Starchy', 3, 5),
('Potato', 'Vegetables', 'Starchy', 3, 5),
('Carrots', 'Vegetables', 'Root', 3, 5),
('Beets', 'Vegetables', 'Root', 3, 5),
('Parsnips', 'Vegetables', 'Root', 3, 5),
('Butternut squash', 'Vegetables', 'Squash', 3, 5),
('Acorn squash', 'Vegetables', 'Squash', 3, 5),
('Pumpkin', 'Vegetables', 'Squash', 3, 5),
('Corn', 'Vegetables', 'Starchy', 3, 5),
('Peas', 'Vegetables', 'Starchy', 3, 5),

-- Dried Fruits
('Dates', 'Fruit', 'Dried', 3, 5),
('Raisins', 'Fruit', 'Dried', 3, 5),
('Dried apricots', 'Fruit', 'Dried', 3, 5),
('Prunes', 'Fruit', 'Dried', 3, 5),

-- TIER 4: LOWER PYRAMID (+3 points)
-- Whole Grains
('Quinoa', 'Grains', 'Whole', 4, 3),
('Brown rice', 'Grains', 'Whole', 4, 3),
('Oats', 'Grains', 'Whole', 4, 3),
('Oatmeal', 'Grains', 'Whole', 4, 3),
('Barley', 'Grains', 'Whole', 4, 3),
('Farro', 'Grains', 'Whole', 4, 3),
('Buckwheat', 'Grains', 'Whole', 4, 3),
('Whole wheat bread', 'Grains', 'Bread', 4, 3),
('Whole wheat pasta', 'Grains', 'Pasta', 4, 3),
('Ezekiel bread', 'Grains', 'Bread', 4, 3),

-- TIER 5: BOTTOM OF PYRAMID (+1 point)
-- Refined Grains
('White rice', 'Grains', 'Refined', 5, 1),
('White bread', 'Grains', 'Refined', 5, 1),
('Pasta', 'Grains', 'Refined', 5, 1),
('Sourdough bread', 'Grains', 'Refined', 5, 1),
('Bagel', 'Grains', 'Refined', 5, 1),
('Tortilla (flour)', 'Grains', 'Refined', 5, 1),
('Tortilla (corn)', 'Grains', 'Refined', 5, 1),
('Crackers', 'Grains', 'Refined', 5, 1),
('Pretzels', 'Grains', 'Refined', 5, 1),

-- ANTI-PYRAMID: LEVEL -5 (Mildly harmful, -2 points)
('Diet Coke', 'Beverages', 'Diet Soda', -5, -2),
('Diet Pepsi', 'Beverages', 'Diet Soda', -5, -2),
('Coke Zero', 'Beverages', 'Diet Soda', -5, -2),
('Diet soda', 'Beverages', 'Diet Soda', -5, -2),
('Sugar-free gum', 'Snacks', 'Sugar-free', -5, -2),
('Splenda', 'Sweeteners', 'Artificial', -5, -2),
('Stevia', 'Sweeteners', 'Artificial', -5, -2),
('Skim milk', 'Dairy', 'Low-fat', -5, -2),
('Fat-free yogurt', 'Dairy', 'Low-fat', -5, -2),
('Light mayo', 'Condiments', 'Low-fat', -5, -2),
('Protein bar', 'Snacks', 'Processed', -5, -2),
('Quest bar', 'Snacks', 'Processed', -5, -2),

-- ANTI-PYRAMID: LEVEL -4 (Moderately harmful, -4 points)
('Potato chips', 'Snacks', 'Chips', -4, -4),
('Lay''s chips', 'Snacks', 'Chips', -4, -4),
('Doritos', 'Snacks', 'Chips', -4, -4),
('Cheetos', 'Snacks', 'Chips', -4, -4),
('Ritz crackers', 'Snacks', 'Crackers', -4, -4),
('Goldfish crackers', 'Snacks', 'Crackers', -4, -4),
('Instant ramen', 'Prepared', 'Instant', -4, -4),
('Cup Noodles', 'Prepared', 'Instant', -4, -4),
('Kraft Mac and Cheese', 'Prepared', 'Boxed', -4, -4),
('Frozen dinner', 'Prepared', 'Frozen', -4, -4),
('Hot Pocket', 'Prepared', 'Frozen', -4, -4),
('American cheese', 'Dairy', 'Processed', -4, -4),
('Velveeta', 'Dairy', 'Processed', -4, -4),
('Margarine', 'Fats', 'Processed', -4, -4),
('Ketchup', 'Condiments', 'Sugary', -4, -4),
('BBQ sauce', 'Condiments', 'Sugary', -4, -4),
('Ranch dressing', 'Condiments', 'Processed', -4, -4),

-- ANTI-PYRAMID: LEVEL -3 (Harmful, -6 points)
('McDonald''s Big Mac', 'Fast Food', 'Burger', -3, -6),
('Burger King Whopper', 'Fast Food', 'Burger', -3, -6),
('Wendy''s burger', 'Fast Food', 'Burger', -3, -6),
('Fast food burger', 'Fast Food', 'Burger', -3, -6),
('French fries', 'Fast Food', 'Fried', -3, -6),
('Chicken nuggets', 'Fast Food', 'Fried', -3, -6),
('Chicken tenders', 'Fast Food', 'Fried', -3, -6),
('Fried chicken', 'Fast Food', 'Fried', -3, -6),
('Chick-fil-A sandwich', 'Fast Food', 'Chicken', -3, -6),
('KFC', 'Fast Food', 'Fried', -3, -6),
('Pizza (fast food)', 'Fast Food', 'Pizza', -3, -6),
('Domino''s pizza', 'Fast Food', 'Pizza', -3, -6),
('Frozen pizza', 'Prepared', 'Frozen', -3, -6),
('Hot dog', 'Protein', 'Processed', -3, -6),
('Bologna', 'Protein', 'Processed', -3, -6),
('Bacon (processed)', 'Protein', 'Processed', -3, -6),
('Pepperoni', 'Protein', 'Processed', -3, -6),
('Deli meat', 'Protein', 'Processed', -3, -6),
('Fish sticks', 'Prepared', 'Frozen', -3, -6),
('Corn dog', 'Fast Food', 'Fried', -3, -6),
('Onion rings', 'Fast Food', 'Fried', -3, -6),
('Taco Bell', 'Fast Food', 'Mexican', -3, -6),
('Chipotle burrito', 'Fast Food', 'Mexican', -3, -6),

-- ANTI-PYRAMID: LEVEL -2 (Very harmful, -8 points)
('Oreos', 'Snacks', 'Cookies', -2, -8),
('Chips Ahoy', 'Snacks', 'Cookies', -2, -8),
('Cookies', 'Snacks', 'Cookies', -2, -8),
('Gatorade', 'Beverages', 'Sports Drink', -2, -8),
('Powerade', 'Beverages', 'Sports Drink', -2, -8),
('Orange juice', 'Beverages', 'Juice', -2, -8),
('Apple juice', 'Beverages', 'Juice', -2, -8),
('Fruit juice', 'Beverages', 'Juice', -2, -8),
('Chocolate milk', 'Dairy', 'Sweetened', -2, -8),
('Sweetened yogurt', 'Dairy', 'Sweetened', -2, -8),
('Yoplait yogurt', 'Dairy', 'Sweetened', -2, -8),
('Frappuccino', 'Beverages', 'Coffee', -2, -8),
('Pumpkin spice latte', 'Beverages', 'Coffee', -2, -8),
('Pancakes', 'Prepared', 'Breakfast', -2, -8),
('Waffles', 'Prepared', 'Breakfast', -2, -8),
('Eggo waffles', 'Prepared', 'Frozen', -2, -8),
('Pancake syrup', 'Condiments', 'Sugary', -2, -8),
('Granola bar', 'Snacks', 'Bar', -2, -8),
('Nature Valley bar', 'Snacks', 'Bar', -2, -8),
('Clif Bar', 'Snacks', 'Bar', -2, -8),
('Muffin', 'Snacks', 'Baked', -2, -8),
('Honey Nut Cheerios', 'Grains', 'Cereal', -2, -8),
('Frosted Mini-Wheats', 'Grains', 'Cereal', -2, -8),

-- ANTI-PYRAMID: LEVEL -1 (Worst, -10 points)
('Coca-Cola', 'Beverages', 'Soda', -1, -10),
('Pepsi', 'Beverages', 'Soda', -1, -10),
('Sprite', 'Beverages', 'Soda', -1, -10),
('Mountain Dew', 'Beverages', 'Soda', -1, -10),
('Dr Pepper', 'Beverages', 'Soda', -1, -10),
('Soda', 'Beverages', 'Soda', -1, -10),
('Red Bull', 'Beverages', 'Energy', -1, -10),
('Monster Energy', 'Beverages', 'Energy', -1, -10),
('Energy drink', 'Beverages', 'Energy', -1, -10),
('Snickers', 'Candy', 'Chocolate', -1, -10),
('M&Ms', 'Candy', 'Chocolate', -1, -10),
('Twix', 'Candy', 'Chocolate', -1, -10),
('Kit Kat', 'Candy', 'Chocolate', -1, -10),
('Reese''s', 'Candy', 'Chocolate', -1, -10),
('Candy bar', 'Candy', 'Chocolate', -1, -10),
('Skittles', 'Candy', 'Sugar', -1, -10),
('Starburst', 'Candy', 'Sugar', -1, -10),
('Gummy bears', 'Candy', 'Sugar', -1, -10),
('Sour Patch Kids', 'Candy', 'Sugar', -1, -10),
('Candy', 'Candy', 'Sugar', -1, -10),
('Donut', 'Snacks', 'Pastry', -1, -10),
('Krispy Kreme', 'Snacks', 'Pastry', -1, -10),
('Dunkin donut', 'Snacks', 'Pastry', -1, -10),
('Cinnamon roll', 'Snacks', 'Pastry', -1, -10),
('Pop-Tarts', 'Snacks', 'Pastry', -1, -10),
('Twinkies', 'Snacks', 'Pastry', -1, -10),
('Little Debbie', 'Snacks', 'Pastry', -1, -10),
('Froot Loops', 'Grains', 'Cereal', -1, -10),
('Lucky Charms', 'Grains', 'Cereal', -1, -10),
('Frosted Flakes', 'Grains', 'Cereal', -1, -10),
('Cocoa Puffs', 'Grains', 'Cereal', -1, -10),
('Cap''n Crunch', 'Grains', 'Cereal', -1, -10),
('Cinnamon Toast Crunch', 'Grains', 'Cereal', -1, -10),
('Ice cream', 'Desserts', 'Frozen', -1, -10),
('Ben & Jerry''s', 'Desserts', 'Frozen', -1, -10),
('Milkshake', 'Desserts', 'Frozen', -1, -10),
('McFlurry', 'Desserts', 'Frozen', -1, -10),
('Cake', 'Desserts', 'Baked', -1, -10),
('Birthday cake', 'Desserts', 'Baked', -1, -10),
('Cupcake', 'Desserts', 'Baked', -1, -10),
('Brownie', 'Desserts', 'Baked', -1, -10),
('Pie', 'Desserts', 'Baked', -1, -10)

ON CONFLICT (name) DO UPDATE SET
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  tier = EXCLUDED.tier,
  points = EXCLUDED.points;
